/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import qytetetjava.MetodoSalirCarcel;
import qytetetjava.Qytetet;
import qytetetjava.Casilla;
import qytetetjava.TipoCasilla;
import qytetetjava.TituloPropiedad;

/**
 *
 * @author Barri
 */
public class ControladorQytetet extends javax.swing.JFrame {
    public Qytetet modeloQytetet;
    /**
     * Creates new form ControladorQytetet
     */
    public ControladorQytetet() {
        initComponents();
    }
        public void actualizar(Qytetet q){        
        vistaQytetet1.Actualizar(q);
        modeloQytetet = q;
        habilitarComenzarTurno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaQytetet1 = new GUIQytetet.VistaQytetet();
        jbTirarDado = new javax.swing.JButton();
        jbPagarCarcel = new javax.swing.JButton();
        jbJugar = new javax.swing.JButton();
        jbComprar = new javax.swing.JButton();
        jbAplicarSorpresa = new javax.swing.JButton();
        jbPasarTurno = new javax.swing.JButton();
        jbGestion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jbTirarDado.setBackground(new java.awt.Color(51, 255, 51));
        jbTirarDado.setText("Intentar Escapar");
        jbTirarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTirarDadoActionPerformed(evt);
            }
        });

        jbPagarCarcel.setBackground(new java.awt.Color(51, 255, 51));
        jbPagarCarcel.setText("Pagar Cárcel");
        jbPagarCarcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPagarCarcelActionPerformed(evt);
            }
        });

        jbJugar.setBackground(new java.awt.Color(51, 255, 51));
        jbJugar.setText("JUGAR");
        jbJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJugarActionPerformed(evt);
            }
        });

        jbComprar.setBackground(new java.awt.Color(51, 255, 51));
        jbComprar.setText("Comprar");
        jbComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprarActionPerformed(evt);
            }
        });

        jbAplicarSorpresa.setBackground(new java.awt.Color(51, 255, 51));
        jbAplicarSorpresa.setText("Aplicar Sorpresa");
        jbAplicarSorpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAplicarSorpresaActionPerformed(evt);
            }
        });

        jbPasarTurno.setBackground(new java.awt.Color(51, 255, 51));
        jbPasarTurno.setText("Pasar Turno");
        jbPasarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPasarTurnoActionPerformed(evt);
            }
        });

        jbGestion.setBackground(new java.awt.Color(51, 255, 51));
        jbGestion.setText("Gestion Inmobiliaria");
        jbGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbTirarDado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPagarCarcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbJugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbComprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPasarTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAplicarSorpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbGestion, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbTirarDado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbPagarCarcel)
                        .addGap(13, 13, 13)
                        .addComponent(jbJugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbComprar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAplicarSorpresa)
                        .addGap(12, 12, 12)
                        .addComponent(jbPasarTurno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbGestion)
                        .addGap(8, 8, 8))
                    .addComponent(vistaQytetet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ActivarGestionInmobiliaria(){
        if (modeloQytetet.getJugadorActual().tengoPropiedades() && !modeloQytetet.getJugadorActual().isEncarcelado()) {
            this.jbGestion.setEnabled(true);
        } else {
            this.jbGestion.setEnabled(false);
        }
    }
    
    public void habilitarComenzarTurno(){
        this.jbComprar.setEnabled(false);
        this.jbPasarTurno.setEnabled(false);
        this.jbAplicarSorpresa.setEnabled(false);
        this.jbPagarCarcel.setEnabled(false);
        this.jbTirarDado.setEnabled(false);
        this.jbGestion.setEnabled(false);
        if(modeloQytetet.getJugadorActual().isEncarcelado()){
            this.jbPagarCarcel.setEnabled(true);
            this.jbTirarDado.setEnabled(true);
        }
        else
            this.jbJugar.setEnabled(true);
    } 
    
    
    private void jbComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprarActionPerformed
        int saldo = modeloQytetet.getJugadorActual().getSaldo();
        int opcion = JOptionPane.showConfirmDialog(null,  "Hola buen señor/a ¿Desea comprar este maravilloso terreno?\nSaldo: " + saldo, "Comprar", JOptionPane.YES_NO_OPTION);
        
        if (opcion == JOptionPane.YES_OPTION) {
            boolean comprado = modeloQytetet.comprarTituloPropiedad();
            if (comprado) {
                this.vistaQytetet1.Actualizar(modeloQytetet);
                JOptionPane.showMessageDialog(this, "Felicidades, has obtenido la propiedad");                
            }
        }
        
        this.jbComprar.setEnabled(false);
        this.jbPasarTurno.setEnabled(true);
        
        ActivarGestionInmobiliaria();
    }//GEN-LAST:event_jbComprarActionPerformed

    private void jbAplicarSorpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAplicarSorpresaActionPerformed
        JOptionPane.showMessageDialog(this, modeloQytetet.getTextoCarta());
        int saldoActual = modeloQytetet.getJugadorActual().getSaldo();        
        boolean encarceladoActual = modeloQytetet.getJugadorActual().isEncarcelado();
        boolean activarGestion = true, activarSiguienteJugador = true;
        
        boolean res = modeloQytetet.aplicarSorpresa();        
        
        this.vistaQytetet1.Actualizar(modeloQytetet);
        
        if (saldoActual != modeloQytetet.getJugadorActual().getSaldo()) {
            JOptionPane.showMessageDialog(this, "Tienes cambios en tu saldo: " + (modeloQytetet.getJugadorActual().getSaldo() - saldoActual));
        }
        
        if (encarceladoActual != modeloQytetet.getJugadorActual().isEncarcelado()) {
            JOptionPane.showMessageDialog(this, "No se si eres consciente de que estás en una mazmorra ");
        }
        
        if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == TipoCasilla.CALLE) {

            this.jbComprar.setEnabled(!res);
            activarGestion = activarSiguienteJugador = false;
        }
        
        this.jbAplicarSorpresa.setEnabled(false);
        this.jbPasarTurno.setEnabled(activarSiguienteJugador);
        
        if (activarGestion) {
            ActivarGestionInmobiliaria();
        }    
    }//GEN-LAST:event_jbAplicarSorpresaActionPerformed

    private void jbTirarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTirarDadoActionPerformed
        boolean resultado =
        modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.TIRANDODADO);
        this.jbPagarCarcel.setEnabled(false);
        this.jbTirarDado.setEnabled(false);

        if(resultado){
            JOptionPane.showMessageDialog(this, "Por esta vez te libras, sales de la carcel");
            this.jbJugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "Gusano miserable, no te escaparás vas a pasar a la sombra un largo tiempo JAJAJAJA");
            this.jbPasarTurno.setEnabled(true);
        }
        this.vistaQytetet1.Actualizar(modeloQytetet);
    }//GEN-LAST:event_jbTirarDadoActionPerformed

    private void jbPagarCarcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPagarCarcelActionPerformed
        boolean resultado =
        modeloQytetet.intentarSalirCarcel(MetodoSalirCarcel.PAGANDOLIBERTAD);
        this.jbPagarCarcel.setEnabled(false);
        this.jbTirarDado.setEnabled(false);

        if(resultado){
            JOptionPane.showMessageDialog(this, "Por esta vez te libras, sales de la carcel");
            this.jbJugar.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "Gusano miserable, no te escaparás vas a pasar a la sombra un largo tiempo JAJAJAJA");
            this.jbPasarTurno.setEnabled(true);
        }
        this.vistaQytetet1.Actualizar(modeloQytetet);
    }//GEN-LAST:event_jbPagarCarcelActionPerformed

    private void jbJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbJugarActionPerformed
         boolean activarSorpresa = false, activarSiguienteJugador = false, activarComprar = false, activarGestion = false;
        int saldoActual = modeloQytetet.getJugadorActual().getSaldo();
        boolean encarceladoActual = modeloQytetet.getJugadorActual().isEncarcelado();
        
        boolean tienePropietario = modeloQytetet.jugar();
        
        this.vistaQytetet1.Actualizar(modeloQytetet); 
        if (modeloQytetet.getJugadorActual().getSaldo() > 0) {
            if (!modeloQytetet.getJugadorActual().isEncarcelado()) {
                if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == qytetetjava.TipoCasilla.CALLE) {
                    if (!tienePropietario) {
                        activarComprar = true;                        
                    } else {
                        String name = ((qytetetjava.Calle)modeloQytetet.getJugadorActual().getCasillaActual()).getTitulo().getPropietario().getNombre();
                        
                        if (name != modeloQytetet.getJugadorActual().getNombre()) {
                            JOptionPane.showMessageDialog(this, "Has caido en la casilla de " + name);
                        }
                        
                        activarSiguienteJugador = true;
                        activarGestion = true;
                    }
                } else if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == qytetetjava.TipoCasilla.SORPRESA) {

                    JOptionPane.showMessageDialog(this, "Has caido en una casilla sorpresa");
                    activarSorpresa = true;
                } else if (modeloQytetet.getJugadorActual().getCasillaActual().getTipo() == qytetetjava.TipoCasilla.IMPUESTO){
                    JOptionPane.showMessageDialog(this, "Has caido en una casilla de tipo Impuesto");
                    activarSiguienteJugador = true;   
                    activarGestion = true;
                } else {
                    activarSiguienteJugador = true;
                    activarSorpresa = false;
                    activarGestion = true;
                }
                
            } else {
                JOptionPane.showMessageDialog(this, "A LAS MAZMORRAS DE VENTORMENTA");
                activarSiguienteJugador = true;
            }
            
        } else {
            this.jbComprar.setEnabled(false);
            this.jbPasarTurno.setEnabled(false);
            this.jbAplicarSorpresa.setEnabled(false);
            this.jbPagarCarcel.setEnabled(false);
            this.jbTirarDado.setEnabled(false);
            this.jbJugar.setEnabled(false);   
            this.jbGestion.setEnabled(false);
            JOptionPane.showMessageDialog(this, modeloQytetet.obtenerRanking().toString());
        }
        
        if (saldoActual != modeloQytetet.getJugadorActual().getSaldo()) {
            JOptionPane.showMessageDialog(this, "Tienes cambios en tu saldo: " + (modeloQytetet.getJugadorActual().getSaldo() - saldoActual));
        }
        
        if (encarceladoActual != modeloQytetet.getJugadorActual().isEncarcelado()) {
            JOptionPane.showMessageDialog(this, "No se si eres consciente de que estás en una mazmorra ");
        }
        this.jbJugar.setEnabled(false);
        this.jbPasarTurno.setEnabled(activarSiguienteJugador);
        this.jbAplicarSorpresa.setEnabled(activarSorpresa);
        this.jbComprar.setEnabled(activarComprar);
        if (activarGestion) {
            ActivarGestionInmobiliaria();
        }
    }//GEN-LAST:event_jbJugarActionPerformed

    private void jbGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionActionPerformed
        Object[] opciones = {"Edificar Casa", "Edificar Hotel", "Vender Propiedad", "Hipotecar Propiedad", "Cancelar Hipoteca"};
        
        int choose = JOptionPane.showOptionDialog(null, "Soldado, que quieres hacer?", "Gestión Inmobiliaria", JOptionPane.DEFAULT_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);
        
        boolean salir = false;
        
        ArrayList<TituloPropiedad> propiedades = modeloQytetet.getJugadorActual().getPropiedades();
        ArrayList<String> nombresPropiedades = new ArrayList();
        
        String[] propiedadesMenu = new String[propiedades.size()];
        
        for (TituloPropiedad propiedad: propiedades) {
            nombresPropiedades.add(propiedad.getNombre());
        }
        
        propiedadesMenu = nombresPropiedades.toArray(propiedadesMenu);
        
        int eleccion = JOptionPane.showOptionDialog(null, "Selecciona tu choza:", "Propiedades", JOptionPane.DEFAULT_OPTION, 
                JOptionPane.INFORMATION_MESSAGE, null, propiedadesMenu, propiedadesMenu[0]);
        
        Casilla casilla = propiedades.get(eleccion).getCasilla();
        
        if (choose == 0) {
            salir = modeloQytetet.edificarCasa(casilla);
            
            if (!salir) {
                JOptionPane.showMessageDialog(this, "No dispones de suficiente oro o has llegado al limite de casas maldito orco");
            }
        } else if (choose == 1) {
            salir = modeloQytetet.edificarHotel(casilla);
            
            if (!salir) {
                JOptionPane.showMessageDialog(this, "No dispones de suficiente oro o has llegado al limite de hoteles o no dispones de suficientes casas maldito humano");
            }
        } else if (choose == 2) {
            salir = modeloQytetet.venderPropiedad(casilla);
            
            if (!salir) {
                JOptionPane.showMessageDialog(this, "No puedes vender esta propiedad por mucho que insistas");
            }
        } else if (choose == 3) {
            salir = modeloQytetet.hipotecarPropiedad(casilla);
            
            if (!salir) {
                JOptionPane.showMessageDialog(this, "Esta propiedad no es hipotecable");
            }
        } else if (choose == 4) {
            salir = modeloQytetet.cancelarHipoteca(casilla);
            
            if (!salir) {
                JOptionPane.showMessageDialog(this, "No puedes cancelar la hipoteca");
            }
        }

        this.vistaQytetet1.Actualizar(modeloQytetet);
        
        ActivarGestionInmobiliaria();
    
    
    }//GEN-LAST:event_jbGestionActionPerformed

    private void jbPasarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPasarTurnoActionPerformed
        modeloQytetet.siguienteJugador();
        actualizar(modeloQytetet);
        
        if (modeloQytetet.getJugadorActual().getSaldo() <= 0) {
            this.jbComprar.setEnabled(false);
            this.jbPasarTurno.setEnabled(false);
            this.jbAplicarSorpresa.setEnabled(false);
            this.jbPagarCarcel.setEnabled(false);
            this.jbTirarDado.setEnabled(false);
            this.jbJugar.setEnabled(false);   
            this.jbGestion.setEnabled(false);
            JOptionPane.showMessageDialog(this, modeloQytetet.obtenerRanking().toString());
        }
    }//GEN-LAST:event_jbPasarTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String[] args){
        ControladorQytetet controladorQytetet= new ControladorQytetet();
        
        CapturaNombreJugadores capturaNombres = new CapturaNombreJugadores(controladorQytetet, true);
        ArrayList<String> nombres= capturaNombres.obtenerNombres();
        
        Dado.createInstance(controladorQytetet);
        Qytetet juego = Qytetet.getInstance();
        juego.inicializarJuego(nombres);
        
       
        controladorQytetet.actualizar(juego);
        controladorQytetet.setVisible(true); //Esta debe ser la última
                                                //línea de código del main
 }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAplicarSorpresa;
    private javax.swing.JButton jbComprar;
    private javax.swing.JButton jbGestion;
    private javax.swing.JButton jbJugar;
    private javax.swing.JButton jbPagarCarcel;
    private javax.swing.JButton jbPasarTurno;
    private javax.swing.JButton jbTirarDado;
    private GUIQytetet.VistaQytetet vistaQytetet1;
    // End of variables declaration//GEN-END:variables
}
